---
language: "python"
python:
  - "3.9"

install:
  - "pip install -r requirements.txt"

before_script:
  - "yamllint --strict *.yml"   # strict treats warning as errors

script:
  - "ansible-playbook test.yml"
